name: workout_tracking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter_timezone: ^3.0.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_calendar_carousel: ^2.4.2
  simple_circular_progress_bar: ^1.0.2
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.0.0
  transparent_image: ^2.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  firebase_auth: ^5.3.1
  flutter_svg: ^2.0.10+1
  toastification: ^2.3.0
  loading_animation_widget: ^1.3.0
  firebase_storage: ^12.3.3
  image_picker: ^1.0.0
  cloud_firestore: ^5.4.4
  flutter_plugin_android_lifecycle: ^2.0.23
  lottie: ^3.1.3
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0 
  freezed: ^2.0.0 
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/images/
    - assets/json/exercises.json
    - assets/json/meals.json
    - assets/Lottie/

